
[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


# ----------------------------------------- setuptools -------------------------------------------
[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


# ----------------------------------------- Project Metadata -------------------------------------
#
[project]
version = "0.0.0.dev31"
name = "LicenseMan"
requires-python = ">=3.10"
dependencies = [
    "LoggerMan == 0.0.0.dev74",
    "PyLinks == 0.0.0.dev57",
    "PkgData == 0.0.0.dev5",
    "PySerials == 0.0.0.dev47",
    "MDit == 0.0.0.dev44",
    "ExceptionMan == 0.0.0.dev44",
    "platformdirs >= 4.3, < 5",
]
