[build-system]
requires = ["setuptools>=61.0","pywin32","pyperclip","selenium==4.8.0","pysmb"]
build-backend = "setuptools.build_meta"

[project]
name = "BoschSapWebGuiAutomation"
version = "0.2.36"
authors = [
  { name="LV Zhichao", email="zhichao.lv@cn.bosch.com" },
]
description = "This package is used for building common automation functions for sap web gui within Bosch"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "pyperclip",
    'pysmb',
    "selenium==4.8.0"
]

[project.urls]
"Homepage" = "https://github.boschdevcloud.com/LZV2SZH/SapWebGuiAutomation"
"Bug Tracker" = "https://github.boschdevcloud.com/LZV2SZH/SapWebGuiAutomation/issues"