[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "demokit"
author = "guillaumefe"
author-email = "guillaume.ferron@gmail.com"
home-page = "https://github.com/guillaumefe"
requires = ["click"]

[tool.flit.scripts]
demokit = "demokit.__main__:main"

