[tool.poetry]
name = "latch-aws"
version = "0.2.2"
description = "Traced and managed aws resources"
authors = ["Max Smolin <max@latch.bio>"]
license = "CC0 1.0"
readme = "README.md"
packages = [{ include = "latch_aws" }]

[tool.poetry.dependencies]
python = "^3.11"
opentelemetry-sdk = "^1.15.0"
latch-data-validation = "^0.1.3"
latch-o11y = "^0.1.4"
aiobotocore = { extras = ["s3"], version = "^2.4.2" }
types-aiobotocore = { extras = ["s3"], version = "^2.4.2" }

[tool.poetry.dev-dependencies]
black = "^22.12.0"
isort = "^5.11.4"
rich = "^13.2.0"
ruff = "^0.0.227"

[tool.black]
preview = true
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.ruff]
pydocstyle = { convention = "google" }
extend-select = ["W", "D", "U", "N", "C", "B", "A", "T", "Q", "M"]
extend-ignore = [
  "A002",
  "A003",

  "E402",
  "E501",
  "E741",

  "C408",
  "C901",

  "T201",

  "D415",

  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D107",
]

[tool.pyright]
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"

reportUnusedImport = "warning"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
