[tool.poetry]
name = "atap-corpus-loader"
version = "1.8.2"
description = "A GUI loader for atap_corpus using the Panel library."
authors = ["Hamish Croser <hamish.croser@sydney.edu.au>"]
readme = "README.md"
documentation = "https://australian-text-analytics-platform.github.io/atap-corpus-loader/DOCS.html"
repository = "https://github.com/Australian-Text-Analytics-Platform/atap-corpus-loader"
license = "MIT"
packages = [{include = "atap_corpus_loader"}]
exclude = ["*/.ipynb_checkpoints/*", "*log.txt"]


[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = ">2.0"
atap-corpus = "~=0.1.15"
panel = "~=1.4.0"
odfpy = "~=1.4.0"
python-docx = "~=1.1.0"
ipywidgets = "~=8.0"
XlsxWriter = "~=3.2.0"
jupyter_panel_proxy = "0.1.0"
gdown = "5.2.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
jupyterlab = "~=4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
