[project]
name = "dkdc-crypto"
version = "0.0.1"
authors = [{ name = "Cody", email = "cody@dkdc.dev" }]
description = "web9 tech for the masses"
readme = "readme.md"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ['cryptography', 'dkdc-env']

[project.optional-dependencies]
dev = ["ruff", "ipython", "jupyter", "nbclient", "ipykernel"]
test = ["pytest"]

[project.urls]
"Homepage" = "https://github.com/dkdc-io/dkdc-crypto"
"Bug Tracker" = "https://github.com/dkdc-io/dkdc-crypto/issues"
