[tool.poetry]
name = "publish-me-new-package"
version = "0.1.0.0"
description = ""
authors = ["xnuinside <xnuinside@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
