[project]
name = "dkdc-todo"
version = "0.0.1"
authors = [{ name = "Cody", email = "cody@dkdc.dev" }]
description = "todo"
readme = "readme.md"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ['dkdc-state', 'dkdc-util']

[project.optional-dependencies]
dev = ["ruff", "ipython", "jupyter", "nbclient", "ipykernel"]
test = ["pytest"]

ui = ["typer", "shiny", "shinyswatch", "shinywidgets"]

[project.urls]
"Homepage" = "https://github.com/dkdc-io/dkdc-todo"
"Bug Tracker" = "https://github.com/dkdc-io/dkdc-todo/issues"

[project.scripts]
"dkdc-todo" = "dkdc_todo.ui.cli:app"
