[project]
name = "funvideo"
version = "1.0.6"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [ "edge-tts>=6.1.18", "moviepy>=2.0.0", "openai>=1.54.5",]
