[tool.poetry]
name = "AxtendedKey"
version = "0.1.4"
description = "Easy AX Permissions for Xcode Builds"
authors = ["Zachary Schuessler <zlschuessler@gmail.com>"]
license = "Unlicense"
readme = "README.md"
repository = "https://github.com/zschuessler/AXtendedKey"
packages = [{include = "axtended_key", from="src"}]

[tool.poetry.dependencies]
python = ">=3.9"
click = "^8.1.7"

[tool.poetry.dev-dependencies]
pytest = "^8.0.0"
isort = "^5.13.2"
black = "^24.10.0"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
axtended-key = "axtended_key.main:main"
