# SPDX-FileCopyrightText: 2024 Tjark Sievers
#
# SPDX-License-Identifier: MIT

[project]
name = "quant-met"
requires-python = ">=3.11,<3.13"

[tool.poetry]
name = "quant-met"
version = "0.0.15"
description = "Calculate superconductivity in flat-band systems."
authors = ["Tjark Sievers <tsievers@physnet.uni-hamburg.de>"]
homepage = "https://quant-met.tjarksievers.de"
repository = "https://github.com/Ruberhauptmann/quant-met"
readme = "README.md"

[tool.poetry.scripts]
quant-met = 'quant_met.cli:cli'

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "^2.1.2"
scipy = "^1.14.1"
matplotlib = "^3.9.2"
pandas = "^2.2.3"
h5py = "^3.12.1"
pydantic = "^2.9.2"
click = "^8.1.7"
numpydantic = "^1.6.4"
tables = "^3.10.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
scriv = "^1.5.1"
jupyter = "^1.0.0"
ipympl = "^0.9.4"
sphinx = "^7.3.7"
myst-parser = "^3.0.1"
nbsphinx = "^0.9.4"
sphinx-gallery = "^0.16.0"
pydata-sphinx-theme = "^0.15.4"
sphinx-design = "^0.6.0"
tox = "^4.15.0"
mypy = "^1.10.0"
pytest = "^8.2.1"
pytest-cov = "^5.0.0"
hypothesis = {extras = ["numpy"], version = "^6.103.0"}
pytest-regressions = "^2.5.0"
numpydoc = "^1.7.0"
ruff = "^0.5.0"
types-pyyaml = "^6.0.12.20240917"
autodoc-pydantic = "^2.2.0"
pytest-integration = "^0.2.3"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Config for ruff
[tool.ruff]
line-length = 100
force-exclude = true
extend-exclude = ["docs/source/conf.py"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203", # one-blank-line-before-class
    "D212", # multi-line-summary-first-line
    "COM812",
    "ISC001",
    "Q000",
    "Q003",
    "S101", # This checks against using assert
    "PLR0913", # This checks against using more than 5 function arguments
    "PLR2004", # Check against "magic values"
    "T201", # Warn about print statements
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
