[project]
name = "botchain"
version = "0.0.2"
authors = [{ name = "Cody", email = "cody@dkdc.dev" }]
description = "chain bots via strings"
readme = "readme.md"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ['pydantic', 'stringflow']

[project.optional-dependencies]
dev = ["ruff", "ipython", "jupyter", "nbclient", "ipykernel"]
test = ["pytest"]

[project.urls]
"Homepage" = "https://github.com/dkdc-io/botchain"
"Bug Tracker" = "https://github.com/dkdc-io/botchain/issues"
