[tool.poetry]
name = "SAGEDbias"
version = "0.0.13"
description = "LLM bias package with customizable benchmark building and analytical tools"
authors = ["HolisticAI"]
readme = "README.md"
packages = [{include = "saged"}]
include = ["external_dependency/*.whl"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.0"
numpy = "^1.22.0"
tqdm = "^4.66.4"
requests = "^2.32.3"
bs4 = "^0.0.2"
wikipedia-api = "^0.7.0"
nltk = "^3.8.1"
scipy = "^1.7.3"
scikit-learn = "^1.4.0"
spacy = "^3.2.1"
transformers = "^4.11.3"
sentence-transformers = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
