[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "nadoo-migration-framework"
version = "0.2.1"
description = "A powerful, Git-based migration framework for NADOO Framework projects"
authors = ["NADOO IT <info@nadoo.it>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/NADOOIT/nadoo-migration-framework"
repository = "https://github.com/NADOOIT/nadoo-migration-framework"
documentation = "https://github.com/NADOOIT/nadoo-migration-framework#readme"
keywords = ["nadoo", "migration", "framework"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.0"
toml = "^0.10.2"
pathlib = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-mock = "^3.12.0"
black = "^23.0.0"
flake8 = "^7.0.0"
mypy = "^1.0.0"

[tool.poetry.scripts]
nadoo-migrate = "nadoo_migration_framework.cli:migrate"
nadoo-init = "nadoo_migration_framework.cli:init_project"
nadoo-publish = "nadoo_migration_framework.cli:publish"


[tool.nadoo]
version = "0.2.1"
