[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rda-toolkit"
version = "0.0.1"
authors = [
  { name="Alec Ramsay", email="alec@davesredistricting.org" },
]
description = "Redistricting analysis tools"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["license", "dependencies"]

[project.urls]
"Homepage" = "https://github.com/rdatools/rdatools"
"Bug Tracker" = "https://github.com/rdatools/rdatools/issues"