[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "telegram-alert-bot"
version = "0.1.1"
authors = [
    { name = "https://github.com/pudjojotaro" },
]
description = "An asynchronous Telegram bot designed for sending alerts and notifications with a message queuing system."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "python-telegram-bot>=20.0",
]

[project.urls]
"Homepage" = "https://github.com/pudjojotaro/telegram-alert-bot" 