[project]
name = "fluentui"
version = "0.0.36"
description = ""
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "polars-lts-cpu>=1.14.0",
    "pydantic>=2.9.2",
    "pyside6>=6.8.0.2",
]

[build-system]
requires = [
    "hatchling",
    "beautifulsoup4",
    "pyside6",
    "pydantic",
    "polars-lts-cpu"
]
build-backend = "hatchling.build"
