[project]
name = "propy_alamstein"
version = "0.1.0"
description = "Final Project for Matt Harrison / MetaSnake's 'Professional Python' Course"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "ipykernel>=6.29.5",
    "ipytest>=0.14.2",
    "requests>=2.32.3",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
    "mypy>=1.13.0",
    "pre-commit>=4.0.1",
    "pyre-check>=0.9.23",
    "pytest>=8.3.3",
    "ruff>=0.7.4",
]
