[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DeepTuner"
version = "0.1.5"
description = "A package for fine-tuning deep learning models with Siamese architecture and triplet loss"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
    {name = "Devasy Patel", email = "patel.devasy.23@gmail.com"}
]
