[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dbxdriverack"
version = "0.0.2"
authors = [{ name = "Matt Kupferman", email = "matt@kupferman.net" }]
maintainers = [{ name = "Matt Kupferman", email = "matt@kupferman.net" }]
description = "Python client library for communicating with dbx DriveRack loudspeaker management systems"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Development Status :: 4 - Beta",
]
dependencies = ["tssplit"]

[project.urls]
Homepage = "https://github.com/mkupferman/dbxdriverack-python"
Documentation = "https://mkupferman.github.io/dbxdriverack-python/"

[tool.setuptools.package-data]
"dbxdriverack" = ["py.typed"]

[project.optional-dependencies]
dev = ["black"]
validate = ["mypy"]
docs = ["sphinx", "sphinxcontrib-napoleon", "sphinx-rtd-theme"]
