[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data-profiler-kit"
version = "0.1.1"
description = "A library to provide quick and insightful data profiling for pandas DataFrames"
readme = "README.md"
authors = [{name = "Najm Eddine Charaf", email = "oldcharaf@gmail.com"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["data", "profiling", "pandas", "analytics"]
dependencies = [
    "pandas>=1.0.0",
    "numpy>=1.18.0",
]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/cnajmeddine/data-profiler"